### ISSUE TITLE
css files are not being loaded

### ISSUE THREAD

**Issue by jsignell** [pyviz/panel#384]
Following the instructions in https://panel.pyviz.org/user_guide/Customization.html, I was trying to move from `raw_css` to `css_files`. I have a file with this in it:

```css
.scrolling {
  overflow: scroll;
}
```

And am loading it in panel like:

```python
pn.extension(css_files=['style.css'])
```

But when using the class, I don't see any effect.
